Fix a linking error in bionic/tests
(CR) : Elevation of privilege vulnerability in libziparchive
(CR)-6762
Mot-CRs-fixed: (CR)

Fix the following linking error by adding liblog in the makefile:
"system/core/libziparchive/zip_archive.cc:277: error: undefined reference to
'__android_log_error_write'"

The error happens because libziparchive has dependency on liblog. This
error affects the downstream branches of nyc-dev.

Bug: 31251826
Test: mma -j32
Change-Id: Ia42909bbbd150ae0ca9f6aa6b14372f2e0aedccf
(cherry picked from commit 3656958a16590d07d1e25587734e000beb437740)
Reviewed-on: https://gerrit.mot.com/918126
SME-Granted: SME Approvals Granted
Tested-by: Jira Key <jirakey@motorola.com>
Reviewed-by: Gunashree Visweswara <gunashre@motorola.com>
Reviewed-by: Jing Ji <a5705c@motorola.com>
Submit-Approved: Jira Key <jirakey@motorola.com>
SLTApproved: Joseph Hansen <wljh16@motorola.com>