Fix a linking error in bionic/tests
Fix the following linking error by adding liblog in the makefile:
"system/core/libziparchive/zip_archive.cc:277: error: undefined reference to
'__android_log_error_write'"

The error happens because libziparchive has dependency on liblog. This
error affects the downstream branches of nyc-dev.

Bug: 31251826
Test: mma -j32
Change-Id: Ia42909bbbd150ae0ca9f6aa6b14372f2e0aedccf